# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_business_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
