# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_businessimages_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimages',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
