# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_businessimages_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessImages',
        ),
    ]
