# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='image',
            field=models.FileField(default='images/none/noThumbnail.jpg', upload_to='images/'),
        ),
    ]
