# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='group',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
    ]
