# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170701_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 19, 35, 21, 69865)),
        ),
    ]
