# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170704_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 23, 13, 8, 169263)),
        ),
        migrations.AlterField(
            model_name='business',
            name='groupID',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
