# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170704_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='isRecommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 15, 16, 39, 29, 38505)),
        ),
    ]
