# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170715_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 19, 12, 45, 763800)),
        ),
    ]
