# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170717_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 19, 19, 33, 369265)),
        ),
    ]
