# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170718_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 22, 27, 41, 874889)),
        ),
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='business',
            name='usefulTip',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
